WebEffectiveWorkersMVC/Models/ErrorViewModel.cs
using System;

namespace WebEffectiveWorkersMVC.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebEffectiveWorkersMVC/Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebEffectiveWorkersMVC.Models {
    public class Project {
        [Key]
        [ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        
        public int? WorkerId { get; set; }
        public virtual Worker Worker { get; set; }
    }
}

WebEffectiveWorkersMVC/Models/Worker.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebEffectiveWorkersMVC.Models {
    public class Worker {
        [Key]
        [ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int Age { get; set; }
        
        public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
    }
}

WebEffectiveWorkersMVC/Controllers/ProjectsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebEffectiveWorkersMVC.DB;
using WebEffectiveWorkersMVC.Models;

namespace WebEffectiveWorkersMVC.Controllers {
    public class ProjectsController: Controller {
        private readonly WPDataContext _context;

        public ProjectsController(WPDataContext context) {
            _context = context;
        }

        public ActionResult Show() {
            return View(_context.Projects.Include(p => p.Worker).ToList());
        }
        
        [HttpGet]
        public ActionResult Add() {
            var workersData = _context.Workers.Include(w => w.Projects).ToList();
            var workers = new SelectList(workersData, "Id", "SecondName");
            ViewBag.Workers = workers;
            return View();
        }

        [HttpPost]
        public ActionResult Add(Project project) {
            _context.Projects.Add(project);
            _context.SaveChanges();
            return Redirect("/projects");
        }

        [HttpGet]
        public ActionResult Edit(int? id) {
            if (id == null) return NotFound();
            var project = _context.Projects.Find(id);
            if (project != null) return View(project);
            return NotFound();
        }

        [HttpPost]
        public ActionResult Edit(Project project) {
            _context.Entry(project).State = EntityState.Modified;
            _context.SaveChanges();
            return Redirect("/projects");
        }
        
        [HttpGet]
        public ActionResult Delete(int? id) {
            if (id == null) return NotFound();
            var project = _context.Projects.Find(id);
            if (project == null) return NotFound();
            return View(project);
        }

        [HttpPost, ActionName("delete")]
        public ActionResult DeleteConfirmed(int id) {
            var project = _context.Projects.Find(id);
            if (project == null) return NotFound();
            _context.Entry(project).State = EntityState.Deleted;
            _context.SaveChanges();
            return Redirect("/projects");
        }
    }
}

WebEffectiveWorkersMVC/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite.Internal.UrlActions;
using Microsoft.EntityFrameworkCore;
using WebEffectiveWorkersMVC.DB;
using WebEffectiveWorkersMVC.Models;

namespace WebEffectiveWorkersMVC.Controllers {
    public class WorkersController : Controller {
        private readonly WPDataContext _context;

        public WorkersController(WPDataContext context) {
            _context = context;
        }
        
        public IActionResult Show() {
            var workers = _context.Workers.Include(w => w.Projects);
            ViewBag.WorkersPrice = 
                workers.ToDictionary(
                    worker => worker.Id, 
                    worker => worker.Projects.Sum(p => p.Price));
            return View(workers);
        }

        [HttpGet]
        public ActionResult Add() {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Worker worker) {
            _context.Add(worker);
            _context.SaveChanges();
            return Redirect("/workers");
        }

        [HttpGet]
        public ActionResult Edit(int? id) {
            if (id == null) return NotFound();
            var worker = _context.Workers.Find(id);
            if (worker != null) return View(worker);
            return NotFound();
        }

        [HttpPost]
        public ActionResult Edit(Worker worker) {
            _context.Entry(worker).State = EntityState.Modified;
            _context.SaveChanges();
            return Redirect("/workers");
        }

        [HttpGet]
        public ActionResult Delete(int? id) {
            if (id == null) return NotFound();
            var worker = _context.Workers.Find(id);
            if (worker == null) return NotFound();
            return View(worker);
        }

        [HttpPost, ActionName("delete")]
        public ActionResult DeleteConfirmed(int id) {
            var worker = _context.Workers.Find(id);
            if (worker == null) return NotFound();
            _context.Entry(worker).State = EntityState.Deleted;
            _context.SaveChanges();
            return Redirect("/workers");
        }
    }
}

WebEffectiveWorkersMVC/Views/Projects/Add.cshtml
@model Project
@{
    ViewBag.Title = "Adding project";
    Layout = "_Layout";
}

<h2>Adding project</h2>

<form method="post" action="">
    @Html.EditorForModel()
    @* @Html.EditorFor(model => model.Name) *@
    @* @Html.EditorFor(model => model.Price) *@
    @* @Html.DropDownListFor(model => model.WorkerId, ViewBag.Workers as SelectList) *@
    <br/>
    <input type="submit" name="Submit" value="Create"/>
</form>

WebEffectiveWorkersMVC/Views/Projects/Delete.cshtml
@model Project
@{
    ViewBag.Title = "Delete worker";
    Layout = "_Layout";
}
<h2>Delete worker @Model.Name</h2>
<dl>
    <dt>Name</dt>
    <dd>@Html.DisplayFor(model => model.Name)</dd>
    
    <dt>Price</dt>
    <dd>@Html.DisplayFor(model => model.Price)</dd>
</dl>
<form method="post" action="">
    <p><input type="submit" value="Delete"/></p>
</form>

WebEffectiveWorkersMVC/Views/Projects/Edit.cshtml
@model Project
@{
    ViewBag.Title = "Editing project";
    Layout = "_Layout";
}

<h2>Editing project @Model.Name</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Submit"/>
</form>

WebEffectiveWorkersMVC/Views/Projects/Show.cshtml
@model IEnumerable<Project>

@{
    ViewBag.Title = "Projects";
    Layout = "_Layout";
}

<div>
    <h3>Projects</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Price</td>
            <td>Owner</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var project in Model) {
            <tr>
                <td>@project.Id</td>
                <td>@project.Name</td>
                <td>@project.Price</td>
                <td>@project.Worker.LastName @project.Worker.FirstName @project.Worker.Patronymic</td>
                <td>
                    <form action="/projects/edit/@project.Id">
                        <input type="submit" value="Edit"/>
                    </form>
                </td>
                <td>
                    <form action="/projects/delete/@project.Id">
                        <input type="submit" value="Delete"/>
                    </form>
                </td>
            </tr>
        }
    </table>
    <p>
        <form action="/projects/add">
            <input type="submit" value="Add project"/>
        </form>
    </p>
</div>

WebEffectiveWorkersMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <title>@ViewData["Title"] - WebEffectiveWorkersMVC</title>
@* *@
     <environment include="Development">
         <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
     </environment>
     <environment exclude="Development">
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
               asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
               asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
               crossorigin="anonymous"
               integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
     </environment>
     <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
     <header>
         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
             <div class="container">
                 <a class="navbar-brand" asp-area="" asp-controller="Workers" asp-action="show">WebEffectiveWorkersMVC</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                         aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                 </button>
                 <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                     <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="workers" asp-action="show">Workers</a>
                         </li>
                         <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="projects" asp-action="show">Projects</a>
                         </li>
                     </ul>
                 </div>
             </div>
         </nav>
     </header>
     <div class="container">
         <partial name="_CookieConsentPartial" />
         <main role="main" class="pb-3">
             @RenderBody()
         </main>
     </div>
@* *@
     <footer class="border-top footer text-muted">
         <div class="container">
             &copy; 2019 - WebEffectiveWorkersMVC
         </div>
     </footer>
@* *@
     <environment include="Development">
         <script src="~/lib/jquery/dist/jquery.js"></script>
         <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
     </environment>
     <environment exclude="Development">
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                 asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                 asp-fallback-test="window.jQuery"
                 crossorigin="anonymous"
                 integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
         </script> 
         <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                 asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                 asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                 crossorigin="anonymous"
                 integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
         </script>
     </environment>
     <script src="~/js/site.js" asp-append-version="true"></script>
@* *@
     @RenderSection("Scripts", required: false)
</body>
</html>

WebEffectiveWorkersMVC/Views/Workers/Add.cshtml
@model Worker
@{
    ViewBag.Title = "Adding worker";
    Layout = "_Layout";
}

<h2>Adding worker</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Create"/>
</form>

WebEffectiveWorkersMVC/Views/Workers/Delete.cshtml
@model Worker
@{
    ViewBag.Title = "Delete worker";
    Layout = "_Layout";
}
<h2>Delete worker @Model.FirstName @Model.LastName</h2>
<dl>
    <dt>Last name</dt>
    <dd>@Html.DisplayFor(model => model.LastName)</dd>
    
    <dt>First name</dt>
    <dd>@Html.DisplayFor(model => model.FirstName)</dd>
    
    <dt>Patronymic</dt>
    <dd>@Html.DisplayFor(model => model.Patronymic)</dd>
    
    <dt>Age</dt>
    <dd>@Html.DisplayFor(model => model.Age)</dd>
</dl>
<form method="post" action="">
    <p><input type="submit" value="Delete"/></p>
</form>

WebEffectiveWorkersMVC/Views/Workers/Edit.cshtml
@model Worker
@{
    ViewBag.Title = "Editing worker";
    Layout = "_Layout";
}

<h2>Editing worker @Model.FirstName @Model.LastName</h2>

<form method="post" action="">
    @Html.EditorForModel()
    <br/>
    <input type="submit" name="Submit" value="Edit"/>
</form>

WebEffectiveWorkersMVC/Views/Workers/Show.cshtml
@model IEnumerable<Worker>
@{
    Layout = "_Layout";
    ViewBag.Title = "Workers";
}
<div>
    <h3>Workers</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Last name</td>
            <td>First name</td>
            <td>Patronymic</td>
            <td>Age</td>
            <td>Total salary</td>
            <td>Projects</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var worker in Model) {
            <tr>
                <td>@worker.Id</td>
                <td>@worker.LastName</td>
                <td>@worker.FirstName</td>
                <td>@worker.Patronymic</td>
                <td>@worker.Age</td>
                <td>@((ViewBag.WorkersPrice as Dictionary<int, decimal>)[worker.Id])</td>
                <td>
                    <ul>
                        @foreach (var project in worker.Projects) {
                            <li>@project.Name</li>
                        }
                    </ul>
                </td>
                <td>
                    <form action="/workers/edit/@worker.Id">
                        <input type="submit" value="Edit"/>
                    </form>
                </td>
                <td>
                    <form action="/workers/delete/@worker.Id">
                        <input type="submit" value="Delete"/>
                    </form>
                </td>
            </tr>
        }
    </table>
    <p>
        <form action="/workers/add">
            <input type="submit" value="Add worker"/>
        </form>
    </p>
</div>